Repository paritytech/polkadot-cloud, pull requests merged in 2023-09, with the labels that each got.

#500 Modals to docs, remove `pages` folder
  app/src/Error.tsx
  app/src/Menu.tsx
  app/src/Router.tsx
  app/src/components/CodeDrawer.tsx
  app/src/config/routes.tsx
  app/src/docs/Modal/ActionItem.tsx
  app/src/docs/Modal/ActionItemWithToggle.tsx
  app/src/docs/Modal/index.mdx
  app/src/docs/Modal/index.tsx
  app/src/docs/modal.mdx
  app/src/pages/Modal.tsx
  app/src/styles/app.scss
Labels: v0.1.2

#499 `SimpleEditor` `standalone` prop, docs own scss file, small fixes
  app/src/docs/Utilities/PlanckToUnit.tsx
  app/src/docs/Utilities/RmCommas.tsx
  app/src/docs/Utilities/UnitToPlanck.tsx
  app/src/docs/Utilities/index.mdx
  app/src/docs/Utilities/ΜinDecimalPlaces.tsx
  app/src/docs/lib/SimpleEditor/index.tsx
  app/src/styles/app.scss
  app/src/styles/docs.scss
Labels: v0.1.2

#531 Hide scrollbars mixin
  app/src/docs/AccountCard/index.mdx
  packages/cloud-core/lib/scss/base/inputs/Switch/index.scss
  packages/cloud-core/lib/scss/base/modal/ModalMotionThreeSection/index.scss
  packages/cloud-core/lib/scss/base/modal/ModalScroll/index.scss
  packages/cloud-core/lib/scss/base/modal/styles.scss
  packages/cloud-core/lib/scss/base/structure/PageTitleTabs/index.scss
  packages/cloud-core/lib/scss/styles/_mixins.scss
  packages/cloud-core/lib/scss/textfield/index.scss
  packages/cloud-core/package.json
  packages/cloud-react/lib/index.tsx
  packages/cloud-react/package.json
Labels: v0.1.2

#534 Cloud theme, restrict other themes to demo
  app/src/Menu.tsx
  app/src/Theme.tsx
  app/src/config/routes.tsx
  app/src/docs/AccountCard/AccountCardPageAdvanced.tsx
  app/src/docs/AccountCard/AccountCardPageAdvancedEllipsis.tsx
  app/src/docs/AccountCard/AccountCardPageAdvancedEllipsisExtreme.tsx
  app/src/docs/AccountCard/AccountCardPageAdvancedExtraComponent.tsx
  app/src/docs/AccountCard/AccountCardPageAdvancedExtraComponentDiff.tsx
  app/src/docs/AccountCard/AccountCardPageAdvancedVariousIconChanges.tsx
  app/src/docs/AccountCard/AccountCardPageSimple.tsx
  app/src/docs/AccountCard/AccountCardPageSimpleMoreProps.tsx
  app/src/docs/AccountCard/AccountCardPageSimpleNoIcon.tsx
  app/src/docs/AccountCard/AccountCardPageStakingSamples.tsx
  app/src/docs/Buttons/ButtonHelp.tsx
  app/src/docs/Buttons/ButtonMono.tsx
  app/src/docs/Buttons/ButtonMonoInvert.tsx
  app/src/docs/Buttons/ButtonPrimary.tsx
  app/src/docs/Buttons/ButtonPrimaryInvert.tsx
  app/src/docs/Buttons/ButtonSecondary.tsx
  app/src/docs/Buttons/ButtonSubmit.tsx
  app/src/docs/Buttons/ButtonSubmitInvert.tsx
  app/src/docs/Buttons/ButtonTab.tsx
  app/src/docs/Buttons/ButtonTertiary.tsx
  app/src/docs/Buttons/ButtonText.tsx
  app/src/docs/Cards/CardInGrid.tsx
  app/src/docs/Cards/CardMono.tsx
  app/src/docs/Cards/CardWithGridSystem.tsx
  app/src/docs/Cards/CardWithGridSystemTwoRows.tsx
  app/src/docs/Extensions/ExtensionsJsx.tsx
  app/src/docs/Extensions/ExtensionsSvg.tsx
  app/src/docs/Icons/PolkIconCustomColors.tsx
  app/src/docs/Icons/PolkIconSizes.tsx
  app/src/docs/Icons/PolkIconThemes.tsx
  app/src/docs/Loaders/LoaderCube.tsx
  app/src/docs/Loaders/LoaderDots.tsx
  app/src/docs/Loaders/LoaderLine.tsx
  app/src/docs/Modal/ActionItem.tsx
  app/src/docs/Modal/ActionItemWithToggle.tsx
  app/src/docs/Odometer/OdometerDiv.tsx
  app/src/docs/Odometer/OdometerH1.tsx
  app/src/docs/Odometer/OdometerH2.tsx
  app/src/docs/Odometer/OdometerH3.tsx
  app/src/docs/Odometer/OdometerH4.tsx
  app/src/docs/Odometer/OdometerH5.tsx
  app/src/docs/Odometer/OdometerP.tsx
  app/src/docs/lib/Demo/index.tsx
  app/src/docs/lib/SimpleEditor/index.tsx
  app/src/docs/lib/SimpleEditor/types.ts
  app/src/main.tsx
  app/src/styles/docs.scss
  packages/cloud-core/lib/template/cloud/fonts/Inter500.woff2
  packages/cloud-core/lib/template/cloud/fonts/Inter600.woff2
  packages/cloud-core/lib/template/cloud/fonts/Inter700.woff2
  packages/cloud-core/lib/template/cloud/fonts/Unbounded.woff2
  packages/cloud-core/lib/template/cloud/fonts/index.css
  packages/cloud-core/lib/template/cloud/index.css
  packages/cloud-core/lib/theme/cloud/index.css
  packages/cloud-core/package.json
  packages/cloud-react/lib/base/modal/ActionItem/index.tsx
Labels: v0.1.2

#538 Overlay fixes
  packages/cloud-core/lib/scss/base/modal/CanvasCard/index.scss
  packages/cloud-core/lib/scss/base/modal/CanvasContainer/index.scss
  packages/cloud-core/lib/scss/base/modal/CanvasContent/index.scss
  packages/cloud-core/lib/scss/base/modal/CanvasScroll/index.scss
  packages/cloud-core/lib/scss/base/modal/ModalCard/index.scss
  packages/cloud-core/lib/scss/base/modal/ModalHeight/index.scss
  packages/cloud-core/lib/scss/base/modal/ModalMotionThreeSection/index.scss
  packages/cloud-core/lib/scss/base/modal/ModalScroll/index.scss
  packages/cloud-core/lib/scss/base/modal/ModalSection/index.scss
  packages/cloud-core/lib/scss/base/modal/styles.scss
  packages/cloud-core/lib/scss/base/structure/PageTitleTabs/index.scss
  packages/cloud-core/package.json
  packages/cloud-react/lib/base/modal/CanvasCard/index.tsx
  packages/cloud-react/lib/base/modal/CanvasContainer/index.tsx
  packages/cloud-react/lib/base/modal/CanvasContent/index.tsx
  packages/cloud-react/lib/base/modal/CanvasScroll/index.tsx
  packages/cloud-react/lib/base/modal/ModalCard/index.tsx
  packages/cloud-react/lib/base/modal/ModalContent/index.tsx
  packages/cloud-react/lib/base/modal/ModalHeight/index.tsx
  packages/cloud-react/lib/base/modal/ModalScroll/index.tsx
  packages/cloud-react/lib/base/modal/types.ts
  packages/cloud-react/lib/overlay/Overlay/Canvas.tsx
  packages/cloud-react/lib/overlay/Overlay/Modal.tsx
  packages/cloud-react/package.json
  yarn.lock
Labels: v0.1.2

#544 Polkicon updates
  app/src/docs/Extensions/ExtensionsJsx.tsx
  app/src/docs/Extensions/ExtensionsSvg.tsx
  app/src/docs/Icons/PolkIconCustomColors.tsx
  app/src/docs/Icons/PolkIconSizes.tsx
  app/src/docs/Icons/PolkIconThemes.tsx
  app/src/styles/app.scss
  packages/cloud-core/lib/scss/base/modal/CanvasScroll/index.scss
  packages/cloud-react/lib/icons/PolkadotIcon/index.tsx
  packages/cloud-react/lib/recipes/AccountCard/index.tsx
  packages/cloud-react/package.json
Labels: v0.1.2

#549 Enhance Extensions docs
  .prettierignore
  app/src/Theme.tsx
  app/src/config/routes.tsx
  app/src/docs/AccountCard/index.mdx
  app/src/docs/Buttons/index.mdx
  app/src/docs/Cards/index.mdx
  app/src/docs/Extensions/ExtensionsJsx.tsx
  app/src/docs/Extensions/ValidatorOperator.tsx
  app/src/docs/Extensions/index.mdx
  app/src/docs/Grid/index.mdx
  app/src/docs/Icons/index.mdx
  app/src/docs/Loaders/index.mdx
  app/src/docs/Modal/index.mdx
  app/src/docs/Odometer/index.mdx
  app/src/docs/Utilities/index.mdx
  app/src/docs/lib/Demo/index.tsx
  app/src/docs/lib/Header/index.tsx
  app/src/docs/lib/NPM/index.tsx
  app/src/docs/lib/Note/index.tsx
  app/src/styles/docs.scss
  packages/cloud-core/lib/template/cloud/index.css
  packages/cloud-core/package.json
Labels: 0.1.3

#556 Add Validators doc, split from Extensions
  app/src/config/routes.tsx
  app/src/docs/Extensions/index.mdx
  app/src/docs/Validators/ValidatorOperator.tsx
  app/src/docs/Validators/index.mdx
  app/src/docs/Validators/index.tsx
Labels: 0.1.3

#561 Rename PolkadotIcon to Polkicon
  app/src/config/routes.tsx
  app/src/docs/AccountCard/AccountCardPageInfo.tsx
  app/src/docs/AccountCard/index.mdx
  app/src/docs/Icons/PolkiconColors.tsx
  app/src/docs/Icons/PolkiconSize.tsx
  app/src/docs/Icons/PolkiconTheme.tsx
  app/src/docs/Icons/index.mdx
  packages/cloud-react/lib/icons/Polkicon/index.tsx
  packages/cloud-react/lib/icons/Polkicon/utils.tsx
  packages/cloud-react/lib/recipes/AccountCard/index.tsx
Labels: 0.1.3

#562 Add app header
  app/src/Footer.tsx
  app/src/Header.tsx
  app/src/Menu.tsx
  app/src/Router.tsx
  app/src/config/routes.tsx
  app/src/docs/Utilities/index.mdx
  app/src/styles/app.scss
  app/src/styles/menu.scss
  app/src/svg/icon.svg
  packages/cloud-core/lib/scss/base/modal/ModalCard/index.scss
Labels: 0.1.3

#563 Add edit page button
  app/src/docs/AccountCard/index.mdx
  app/src/docs/AccountCard/index.tsx
  app/src/docs/Buttons/index.mdx
  app/src/docs/Buttons/index.tsx
  app/src/docs/Cards/index.mdx
  app/src/docs/Cards/index.tsx
  app/src/docs/Extensions/index.mdx
  app/src/docs/Extensions/index.tsx
  app/src/docs/Grid/index.mdx
  app/src/docs/Grid/index.tsx
  app/src/docs/Icons/index.mdx
  app/src/docs/Icons/index.tsx
  app/src/docs/Loaders/index.mdx
  app/src/docs/Loaders/index.tsx
  app/src/docs/Modal/index.mdx
  app/src/docs/Modal/index.tsx
  app/src/docs/Odometer/index.mdx
  app/src/docs/Odometer/index.tsx
  app/src/docs/Switch/index.mdx
  app/src/docs/Switch/index.tsx
  app/src/docs/Textfield/index.mdx
  app/src/docs/Textfield/index.tsx
  app/src/docs/Utilities/index.mdx
  app/src/docs/Utilities/index.tsx
  app/src/docs/Validators/index.mdx
  app/src/docs/Validators/index.tsx
  app/src/docs/lib/Edit/index.tsx
  app/src/styles/app.scss
  app/src/styles/docs.scss
Labels: 0.1.3

#564 Rb collapsable menu
  app/src/Menu.tsx
  app/src/Menu/Category.tsx
  app/src/Menu/index.tsx
  app/src/config/routes.tsx
  app/src/styles/app.scss
  app/src/styles/menu.scss
Labels: 0.1.3

#572 Utils `peerDependencies` to `dependencies`
  packages/utils/package.json
  yarn.lock
Labels: 0.1.3

#573 `@polkadot-cloud/react` move some `peerDependencies` to `dependencies`
  packages/cloud-react/package.json
  yarn.lock
Labels: 0.1.3

#577 Package status taxonomy
  app/src/config/routes.tsx
  app/src/docs/AccountCard/index.mdx
  app/src/docs/Buttons/index.mdx
  app/src/docs/Cards/index.mdx
  app/src/docs/Charts/index.mdx
  app/src/docs/Extensions/index.mdx
  app/src/docs/Grid/index.mdx
  app/src/docs/Icons/index.mdx
  app/src/docs/Loaders/index.mdx
  app/src/docs/Modal/index.mdx
  app/src/docs/Odometer/index.mdx
  app/src/docs/Switch/index.mdx
  app/src/docs/Textfield/index.mdx
  app/src/docs/Utilities/index.mdx
  app/src/docs/Validators/index.mdx
  app/src/docs/lib/Header/index.tsx
  app/src/docs/lib/Label/index.tsx
  app/src/styles/docs.scss
  app/src/styles/menu.scss
Labels: 0.1.3

#583 Add basic overlay docs
  app/src/config/routes.tsx
  app/src/docs/Overlay/OpenOverlay.tsx
  app/src/docs/Overlay/OverlayBasic.tsx
  app/src/docs/Overlay/OverlayConfig.tsx
  app/src/docs/Overlay/OverlayProvider.tsx
  app/src/docs/Overlay/index.mdx
  app/src/docs/Overlay/index.tsx
  app/src/styles/docs.scss
Labels: 0.1.3

#584 Menu updates
  app/src/Menu/Category.tsx
  app/src/config/routes.tsx
  app/src/docs/Extensions/index.mdx
  app/src/docs/Validators/index.mdx
  app/src/styles/menu.scss
Labels: 0.1.3

#586 Enhance Polkicon docs
  app/src/config/routes.tsx
  app/src/docs/Icons/index.mdx
  app/src/docs/Polkicon/PolkiconColors.tsx
  app/src/docs/Polkicon/PolkiconSize.tsx
  app/src/docs/Polkicon/PolkiconTheme.tsx
  app/src/docs/Polkicon/index.mdx
  app/src/docs/Polkicon/index.tsx
Labels: 0.1.3

#588 Tidy up Odometer docs
  app/src/docs/Charts/DonutPiePageDifferentSizes.tsx
  app/src/docs/Charts/DonutPiePageDifferentSpeed.tsx
  app/src/docs/Odometer/OdometerDiv.tsx
  app/src/docs/Odometer/OdometerH1.tsx
  app/src/docs/Odometer/OdometerH2.tsx
  app/src/docs/Odometer/OdometerH3.tsx
  app/src/docs/Odometer/OdometerH4.tsx
  app/src/docs/Odometer/OdometerH5.tsx
  app/src/docs/Odometer/OdometerP.tsx
  app/src/docs/Odometer/index.mdx
  packages/cloud-core/lib/template/cloud/index.css
Labels: 0.1.3

#597 Redesign doc note
  app/src/docs/Extensions/index.mdx
  app/src/docs/lib/Note/index.tsx
  app/src/styles/docs.scss
  app/src/svg/info.svg
  packages/cloud-core/lib/theme/cloud/index.css
Labels: 0.1.3

#603 Add default path logic
  app/src/Menu/Category.tsx
  app/src/Menu/index.tsx
  app/src/config/routes.tsx
Labels: 0.1.3

#616 Move Charts to Stable components
  app/src/config/routes.tsx
  app/src/docs/Charts/index.mdx
Labels: 0.1.3

#623 Move `ExtensionsProvider` to the cloud
  packages/cloud-react/lib/connect/ExtensionsProvider/defaults.ts
  packages/cloud-react/lib/connect/ExtensionsProvider/index.tsx
  packages/cloud-react/lib/connect/ExtensionsProvider/types.ts
  packages/cloud-react/lib/hooks.tsx
  packages/cloud-react/lib/overlay/Overlay/Background.tsx
  packages/cloud-react/lib/overlay/Overlay/Canvas.tsx
  packages/cloud-react/lib/overlay/Overlay/Modal.tsx
  packages/cloud-react/lib/overlay/Overlay/index.tsx
  packages/cloud-react/lib/overlay/OverlayProvider/defaults.ts
  packages/cloud-react/lib/overlay/OverlayProvider/index.tsx
  packages/cloud-react/lib/overlay/OverlayProvider/types.ts
  packages/cloud-react/package.json
  yarn.lock
Labels: 0.1.4
